### ISSUE TITLE
Upgrade to Android Studio Flamingo | 2022.2.1

### ISSUE THREAD

**Issue by ghusta** [ghusta/android-docker-search#338]
See :

- https://developer.android.com/studio/releases

And also :

- Android Gradle plugin 8.0.0

---

### Tasks

- [ ] AGP 8.0 (https://developer.android.com/build/releases/gradle-plugin)
- [ ] #325 (https://developer.android.com/build/releases/gradle-plugin#updating-gradle) 
- [ ] #339 (https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp)
- [ ] Refactor plugins declaration in Gradle build (https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block)
